### ISSUE TITLE
crtl-c doenst work in start wars screensaver

### ISSUE THREAD

**Issue by b10w60** [brunobraga/termsaver#25]
crtl-c doenst work in start wars screensaver. Couldn't even disconnect with the usual telnet sequence. Hat to sigkill termserver.

**Comment by brunobraga** [comment]
Thanks for letting us know.

Yeah, never thought on leaving star wars in there in the first place... stayed by mistake, but it was removed long time ago... I just never had the chance to push the updates to Debian.
I will leave your issue opened, as a reminder to check that it is out of the list... 

Just to give context, I didn't want to leave it because of the need to download a big file every time prior to lading the screen... would be looking at other options to implement that, but ended up going in the direction of plugins, but it is work in progress.

**Comment by brunobraga** [comment]
dealing with this in Issue #26
