### ISSUE TITLE
How to install a simple plugin?

### ISSUE THREAD

**Issue by NonlinearFruit** [brunobraga/termsaver#36]
What is the simplest way to add a screen saver to my local termsaver?

I've seen the figlet plugin and it is a little bulky. I wrote a screen but I'm having difficulty getting termsaver to pick it up. Here is my plugin.

```
import time
import sys

from termsaverlib.screen.base import ScreenBase
from termsaverlib.screen.helper.typing import TypingHelperBase
from termsaverlib.screen.helper.position import PositionHelperBase
from termsaverlib import common, exception, constants
from termsaverlib.i18n import _


class LocalQuotesScreen(ScreenBase, TypingHelperBase, PositionHelperBase):

    sleep_between_items = 0
    char_delay = 0.15
    line_delay = 1.5
    data = None

    def __init__(self):
        ScreenBase.__init__(self, "quotes", "display quotes from local file", {
            'opts': ':p:',
            'long_opts': ['path='],
        })

    def _usage_options_example(self):
        print _(""" """)

    def _parse_args(self, prepared_args):
        for option, arg in prepared_args[0]:
            if option in ("-p", "--path"):
                self._read_file_into_data(arg)

    def _read_file_into_data(self, path):
        with open(path, 'r') as content_file:
            self.data = content_file.read().split("\n\n")

    def _run_cycle(self):
        self.clear_screen()

        for item in self.data:
            self.get_terminal_size()
            item = self.center_text_vertically(item)
            item = self.center_text_horizontally(item)

            ##
            lines = item.split('\n')
            for index, line in enumerate(lines):
                for char in line:
                    sys.stdout.write(char)
                    if char != ' ':
                        time.sleep(self.char_delay)
                    sys.stdout.flush()
                sys.stdout.write('\n')
                if not line.isspace():
                    time.sleep(self.line_delay)
            ##

            time.sleep(self.sleep_between_items)

            self.clear_screen()
```

**Comment by brunobraga** [comment]
Hi, thanks for taking the time to try this out.

The plugins were part of the original idea but I never got to finish the integration piece with things like autocomplete, etc.  The essence is that this code, once available in the termsaverlib/plugins folder, should be loaded automatically in the list of available screensavers. I haven't played with this in years, but from memory it worked with the sample code.

What you can do as well, since this is very similar to the existing screens, is to fork the original termsaver code, add it into termsaverlib/screen. Do your diligence (test, make sure it works under different conditions, eg. Linux vs. Mac vs. Windows, etc) and submit a pull request, and I'd be happy to bring this in to the main code.

The idea of the plugins were designed more to accommodate screens that need external packages (I'd prefer to keep termsaver package as 'clean' as possible). A good example for this is the figlet package, or some others that have been suggested in the issue list.

Thanks again for your contribution!
