### ISSUE TITLE
asciiartfarts - randomization.

### ISSUE THREAD

**Issue by bartoszek** [brunobraga/termsaver#40]
Since `asciiartfarts` is dead since 2014 could we have a randomization option to start farts display at different offset each time?

**Comment by brunobraga** [comment]
Yeah, it's based on RSS so that's why the data coming in does not look into the past...
You can use the rssfeed option for other feeds though.

for the asciiartfarts, you could build a parser to get the ramdom.cgi page extracting only the art content as the "feed", on a continuous loop... 

Feel free to fork this and propose a solution if you are into coding...
